spring.application.name=studymate
spring.datasource.url=jdbc:postgresql://localhost:5432/studymate
spring.datasource.username=studymate_user
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update